### ISSUE TITLE
Error loading godot_llm.gdextension

### ISSUE THREAD

**Issue by MauroPle** [Adriankhl/godot-llm-template#2]
(running on mac book pro 2,3 GHz Intel Core i7 quad-core 16 GB 1600 MHz DDR3, Godot version 4.2stable)
Godot just doesn't let me open the extension and instead sends this error messages:

  Can't open dynamic library: /Users/mauro/Desktop/Godot LLM Template/addons/godot_llm/bin/libgodot_llm.darwin.release.universal.dylib. Error: dlopen(/Users/mauro/Desktop/Godot LLM Template/addons/godot_llm/bin/libgodot_llm.darwin.release.universal.dylib, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
    Referenced from: /Users/mauro/Desktop/Godot LLM Template/addons/godot_llm/bin/libgodot_llm.darwin.release.universal.dylib (which was built for Mac OS X 14.0)
    Expected in: /usr/lib/libc++.1.dylib
  .
  core/extension/gdextension.cpp:719 - GDExtension dynamic library not found: /Users/mauro/Desktop/Godot LLM Template/addons/godot_llm/bin/libgodot_llm.darwin.release.universal.dylib
  Failed loading resource: res://addons/godot_llm/godot_llm.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

so it's impossible to activate the plugin and run the project

**Comment by MauroPle** [comment]
Do you have any advice?

**Comment by Adriankhl** [comment]
The current mac build relies on [github action runner image](https://github.com/actions/runner-images/tree/main?tab=readme-ov-file#available-images), and gpu llama.cpp for x64 [can't be built](https://github.com/ggerganov/llama.cpp/blob/master/.github/workflows/build.yml#L105-L109) on the standard macos 14 image because of the lack of gpu there. 

Also because of the fact that intel mac intel mac has been discontinued for some years, I decided not to deal with this in my build. If you are interested in using the plugin on intel mac, building from source should be quite easy, something like:
```
          mkdir build
          cd build
          cmake .. --preset macos-metal-release
          cmake --build . --config Release -j $(sysctl -n hw.logicalcpu)
```

**Comment by MauroPle** [comment]
Ok! Thanks. Should I close the issue?

**Comment by Adriankhl** [comment]
Sure
